### ISSUE TITLE
VUE node server does not start

### ISSUE THREAD

**Issue by daveinglis** [BME-nodeservers/docs#14]
Installed on eisy (PG3x)
added user/pass configuration but the logs indicate a missing python module

> 2024-12-06 15:37:33.287 MainThread udi_interface      INFO     polylogger:set_basic_config: set_basic_config: enable=True level=30
2024-12-06 15:37:33.287 MainThread udi_interface      INFO     __init__:<module>: UDI interface initializing
2024-12-06 15:37:33.287 MainThread udi_interface      INFO     __init__:<module>: User=0021b9026ee6_11
2024-12-06 15:37:33.287 MainThread udi_interface      INFO     __init__:<module>: Home=/var/polyglot/pg3/ns/0021b9026ee6_11
2024-12-06 15:37:33.287 MainThread udi_interface      INFO     __init__:<module>: Node Server Path=/var/polyglot/pg3/ns/0021b9026ee6_11
2024-12-06 15:37:33.287 MainThread udi_interface      INFO     __init__:<module>: PG3INIT=eyJ1dWlkIjoiMDA6MjE6Yjk6MDI6NmU6ZTYiLCJwcm9maWxlTnVtIjoxMSwibG9nTGV2ZWwiOiJFUlJPUiIsInRva2VuIjoiSylrQT1mYlVSc1R6MzFTKiIsIm1xdHRIb3N0IjoibG9jYWxob3N0IiwibXF0dFBvcnQiOjg4ODMsInNlY3VyZSI6MSwiaXNQRzN4Ijp0cnVlLCJwZzNWZXJzaW9uIjoiMy4yLjI3IiwiaXN5VmVyc2lvbiI6IjUuOC40IiwiZWRpdGlvbiI6IkZyZWUifQ==
2024-12-06 15:37:33.287 MainThread udi_interface      INFO     __init__:<module>: Loading interface module
2024-12-06 15:37:33.329 MainThread udi_interface      INFO     interface:<module>: Loading MQTT module
2024-12-06 15:37:33.867 MainThread udi_interface      INFO     interface:<module>: MQTT module loaded
2024-12-06 15:37:34.059 MainThread udi_interface      INFO     __init__:<module>: Loading udi_interface module
2024-12-06 15:37:34.059 MainThread udi_interface      INFO     __init__:<module>: Loading node module
2024-12-06 15:37:34.059 MainThread udi_interface      INFO     __init__:<module>: Loading custom module
2024-12-06 15:37:34.059 MainThread udi_interface      INFO     __init__:<module>: Loading isy module
2024-12-06 15:37:34.059 MainThread udi_interface      INFO     __init__:<module>: Loading OAuth module
2024-12-06 15:37:34.060 MainThread udi_interface      INFO     __init__:<module>: UDI interface initialized
2024-12-06 15:37:34.060 MainThread udi_interface      INFO     __init__:<module>: UDI Python Interface for Polyglot version 3 3.3.14 Starting...
2024-12-06 15:37:34.062 MainThread udi_interface      ERROR    udi_interface:write: Traceback (most recent call last):
2024-12-06 15:37:34.062 MainThread udi_interface      ERROR    udi_interface:write: File "/var/polyglot/pg3/ns/0021b9026ee6_11/vue.py", line 10, in <module>
2024-12-06 15:37:34.062 MainThread udi_interface      ERROR    udi_interface:write: import pyemvue
2024-12-06 15:37:34.062 MainThread udi_interface      ERROR    udi_interface:write: File "/var/polyglot/pg3/ns/0021b9026ee6_11/pyemvue/__init__.py", line 2, in <module>
2024-12-06 15:37:34.062 MainThread udi_interface      ERROR    udi_interface:write: from pyemvue.pyemvue import PyEmVue
2024-12-06 15:37:34.062 MainThread udi_interface      ERROR    udi_interface:write: File "/var/polyglot/pg3/ns/0021b9026ee6_11/pyemvue/pyemvue.py", line 8, in <module>
2024-12-06 15:37:34.063 MainThread udi_interface      ERROR    udi_interface:write: import boto3
2024-12-06 15:37:34.063 MainThread udi_interface      ERROR    udi_interface:write: ModuleNotFoundError
2024-12-06 15:37:34.063 MainThread udi_interface      ERROR    udi_interface:write: :
2024-12-06 15:37:34.063 MainThread udi_interface      ERROR    udi_interface:write: No module named 'boto3'

**Comment by bpaauwe** [comment]
I believe you need to install the development packages on the Polisy/eisy so that it has the modules needed for the plug-in.
